version: '3'
services:
  frontend:
    image: node:latest
    container_name: frontend-container
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
      - database
    restart: always
    network_mode: "host"
    command: npm start
  
  backend:
    build:
      context: ./backend
    container_name: backend-container
    hostname: backend
    volumes:
      - ./backend:/app
    depends_on:
      - database
    restart: always
    network_mode: "host"
  
  database:
    image: postgres:13
    container_name: database-container
    hostname: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    network_mode: "host"

volumes:
  postgres_data:
