# This workflow will build dan testing app.
name: Dev Testing 🔎 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env

      - name: Build and Run Container
        run: |
          sudo docker compose up database-pacmail backend-pacmail frontend-pacmail --build --detach

      - name: Hit Endpoint
        run: |
          sleep 10
          curl ${{ secrets.PROD_URL_1 }}
          curl ${{ secrets.PROD_URL_2 }}
          
      - name: Testing
        run: |
          pip install -r testing/requirements.txt
          python3 testing/test_signup.py
